# Generated by Django 5.1.6 on 2025-03-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.BigIntegerField()),
                ('Semester', models.IntegerField()),
                ('Course_Code', models.TextField(blank=True, null=True)),
                ('Attendance_Percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('staff_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOCIATE PROFESSOR', 'Associate Professor'), ('ASSISTANT PROFESSOR', 'Assistant Professor')], max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('qualification', models.TextField()),
                ('specialization', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('date_of_joining', models.DateField()),
                ('present_address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('teaching_research_experience', models.IntegerField(default=0)),
                ('industry_experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.BigIntegerField()),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=2)),
                ('staff_name', models.TextField()),
                ('Course_Code', models.TextField()),
                ('Course_Name', models.CharField(max_length=100)),
                ('Date_Attended', models.DateField()),
                ('From_Time', models.TimeField()),
                ('To_Time', models.TimeField()),
                ('No_of_Hours', models.SmallIntegerField()),
                ('Is_Present', models.BooleanField(default=False)),
            ],
        ),
    ]
