# Generated by Django 5.1.6 on 2025-03-18 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffnsn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(choices=[('M.Phil', 'M.Phil'), ('M.E', 'M.E'), ('M.Sc', 'M.Sc'), ('Ph.D', 'Ph.D')], max_length=20)),
                ('awarded', models.IntegerField(default=0)),
                ('guidance', models.IntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_guidance', to='staffnsn.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'discipline')},
            },
        ),
    ]
