# Generated by Django 5.1.6 on 2025-03-18 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffnsn', '0002_researchguidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CONFERENCE_NATIONAL', 'Conference - National'), ('CONFERENCE_INTERNATIONAL', 'Conference - International'), ('SEMINAR', 'Seminar'), ('SYMPOSIA', 'Symposia'), ('WORKSHOP', 'Workshop')], max_length=25)),
                ('role', models.CharField(choices=[('ATTENDED', 'Attended'), ('CONDUCTED', 'Conducted')], max_length=10)),
                ('count', models.IntegerField(default=0)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='staffnsn.faculty')),
            ],
            options={
                'unique_together': {('faculty', 'event_type', 'role')},
            },
        ),
    ]
