# Generated by Django 5.1.6 on 2025-03-18 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffnsn', '0003_academicevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('MAJOR', 'Major'), ('MINOR', 'Minor')], max_length=5)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('ONGOING', 'Ongoing')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to='staffnsn.faculty')),
            ],
        ),
    ]
