# Generated by Django 5.1.6 on 2025-03-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffnsn', '0004_researchproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_type', models.CharField(choices=[('JOURNAL_INTERNATIONAL', 'Journal - International'), ('JOURNAL_NATIONAL', 'Journal - National'), ('CONFERENCE_INTERNATIONAL', 'Conference - International'), ('CONFERENCE_NATIONAL', 'Conference - National'), ('BOOK', 'Book'), ('POPULAR_ARTICLE', 'Popular Article')], max_length=30)),
                ('authors', models.TextField()),
                ('title', models.TextField()),
                ('journal_name', models.CharField(max_length=255)),
                ('volume', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('pages', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='staffnsn.faculty')),
            ],
        ),
    ]
